// flow-typed signature: a7b1ac177d4fd8857772926ef2c9c305
// flow-typed version: <<STUB>>/swal_v^0.1.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swal/build/build' {
  declare module.exports: any;
}

declare module 'swal/build/check-versions' {
  declare module.exports: any;
}

declare module 'swal/build/dev-client' {
  declare module.exports: any;
}

declare module 'swal/build/dev-server' {
  declare module.exports: any;
}

declare module 'swal/build/utils' {
  declare module.exports: any;
}

declare module 'swal/build/webpack.base.conf' {
  declare module.exports: any;
}

declare module 'swal/build/webpack.dev.conf' {
  declare module.exports: any;
}

declare module 'swal/build/webpack.prod.conf' {
  declare module.exports: any;
}

declare module 'swal/config/dev.env' {
  declare module.exports: any;
}

declare module 'swal/config/index' {
  declare module.exports: any;
}

declare module 'swal/config/prod.env' {
  declare module.exports: any;
}

declare module 'swal/config/test.env' {
  declare module.exports: any;
}

declare module 'swal/src/main' {
  declare module.exports: any;
}

declare module 'swal/test/unit/index' {
  declare module.exports: any;
}

declare module 'swal/test/unit/karma.conf' {
  declare module.exports: any;
}

declare module 'swal/test/unit/specs/Hello.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swal/build/build.js' {
  declare module.exports: $Exports<'swal/build/build'>;
}
declare module 'swal/build/check-versions.js' {
  declare module.exports: $Exports<'swal/build/check-versions'>;
}
declare module 'swal/build/dev-client.js' {
  declare module.exports: $Exports<'swal/build/dev-client'>;
}
declare module 'swal/build/dev-server.js' {
  declare module.exports: $Exports<'swal/build/dev-server'>;
}
declare module 'swal/build/utils.js' {
  declare module.exports: $Exports<'swal/build/utils'>;
}
declare module 'swal/build/webpack.base.conf.js' {
  declare module.exports: $Exports<'swal/build/webpack.base.conf'>;
}
declare module 'swal/build/webpack.dev.conf.js' {
  declare module.exports: $Exports<'swal/build/webpack.dev.conf'>;
}
declare module 'swal/build/webpack.prod.conf.js' {
  declare module.exports: $Exports<'swal/build/webpack.prod.conf'>;
}
declare module 'swal/config/dev.env.js' {
  declare module.exports: $Exports<'swal/config/dev.env'>;
}
declare module 'swal/config/index.js' {
  declare module.exports: $Exports<'swal/config/index'>;
}
declare module 'swal/config/prod.env.js' {
  declare module.exports: $Exports<'swal/config/prod.env'>;
}
declare module 'swal/config/test.env.js' {
  declare module.exports: $Exports<'swal/config/test.env'>;
}
declare module 'swal/src/main.js' {
  declare module.exports: $Exports<'swal/src/main'>;
}
declare module 'swal/test/unit/index.js' {
  declare module.exports: $Exports<'swal/test/unit/index'>;
}
declare module 'swal/test/unit/karma.conf.js' {
  declare module.exports: $Exports<'swal/test/unit/karma.conf'>;
}
declare module 'swal/test/unit/specs/Hello.spec.js' {
  declare module.exports: $Exports<'swal/test/unit/specs/Hello.spec'>;
}
