// flow-typed signature: bd937d93a65e206554c2a49bf8a48b40
// flow-typed version: <<STUB>>/@babel/preset-typescript_v^7.9.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-typescript/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-typescript/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-typescript/lib/index'>;
}
